services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: balance_app
        restart: unless-stopped
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - balance_net

    nginx:
        image: nginx:alpine
        container_name: balance_nginx
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - balance_net
        depends_on:
            - app

    db:
        image: postgres:15-alpine
        container_name: balance_db
        restart: always
        environment:
            POSTGRES_DB: balance_app
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: secret
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - balance_net

volumes:
    db_data:

networks:
    balance_net:
        driver: bridge
